### ISSUE TITLE
Message not referenced

### ISSUE THREAD

**Issue by PawelWesolowski** [Itelios/bitrise-steps-git-tag#2]
The message for tag is ${tag_message}
I am trying to put a variable in the message - maybe it causes this issue?
![image](https://cloud.githubusercontent.com/assets/17248853/14421695/56f7313e-ffd3-11e5-9da8-60720d64e747.png)

**Comment by Reedyuk** [comment]
Yes, I'm also getting this issue.

**Comment by Reedyuk** [comment]
i have forked and fixed it.
https://github.com/Reedyuk/bitrise-steps-git-tag
awaiting a pull, you can use my step directly for now.

**Comment by mseijas** [comment]
@vincentsaluzzo Any chance we can get a pull for this fix? ^ thx!

**Comment by vincentsaluzzo** [comment]
Thank you for the PR, I've merged it. @Reedyuk
